name: Kernel PGO Generate (Final Stable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Install minimal deps
        run: |
          sudo apt update -qq
          sudo apt install -y bc flex bison

      - name: Clone Proton Clang (STABLE)
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Verify clang
        run: |
          ls clang/bin
          clang/bin/clang --version
          clang/bin/ld.lld --version

      - name: Clone Kernel
        run: |
          git clone --depth=1 -b android14-6.1-staging \
          https://github.com/ramabondanp/android_kernel_common-6.1.git kernel

      - name: Build Kernel (PGO Generate)
        run: |
          cd kernel

          export PATH="$GITHUB_WORKSPACE/clang/bin:$PATH"

          make O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 gki_defconfig

          # PGO aç
          scripts/config --file out/.config --enable CONFIG_DEBUG_FS
          scripts/config --file out/.config --enable CONFIG_PGO_CLANG
          scripts/config --file out/.config --enable CONFIG_PGO_CLANG_KERNEL

          make O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 olddefconfig

          make -j$(nproc) O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 \
            Image

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel-pgo-generate
          path: kernel/out/arch/arm64/boot/Image
